version: '2'

services:
  db:
    image: mdillon/postgis:9.4
    environment:
     - POSTGRES_DB=recifegourmet_api_development
     - POSTGRES_USER=root

  redis:
    image: redis

  sidekiq:
    depends_on:
     - db
     - redis
    build: .
    command: bundle exec sidekiq
    volumes:
     - .:/app
    environment:
     - ENABLE_DEBUG_SERVER=true
     - INSTRUMENTATION_ENABLED=true
     - RECIFEGOURMET_API_REDIS_URL=redis://redis:6379/0

  web:
    depends_on:
     - db
     - redis
    build: .
    command: bin/rails s --port 3000 --binding 0.0.0.0
    volumes:
     - .:/app
    environment:
     - ENABLE_DEBUG_SERVER=true
     - INSTRUMENTATION_ENABLED=true
     - RECIFEGOURMET_API_REDIS_URL=redis://redis:6379/0
    ports:
     - '3000:3000'
     - '8989:8989'
