default: &default
  adapter: postgis
  encoding: unicode
  pool: 30

development:
  <<: *default
  host: db
  database: recifegourmet_api_development

production:
  <<: *default
  host: <%= ENV['PETLIG_DATABASE_HOST'] %>
  database: <%= ENV['PETLIG_DATABASE_NAME'] %>
  username: <%= ENV['PETLIG_DATABASE_USERNAME'] %>
  password: <%= ENV['PETLIG_DATABASE_PASSWORD'] %>
